### PR TITLE
add support for start_date only setup in work

### PR DESCRIPTION
**Pull request by divyenduz**
Closes https://github.com/TimDaub/jsonresume-theme-paper/issues/10

### CODE REVIEW

**Comment by TimDaub** [comment]
Thank you :)

**Comment by TimDaub** [comment]
Released via #12

**Comment by TimDaub** [comment]
@divyenduz I've added you as a contributor. If you have more improvements, let's try to still keep doing peer reviews via Github PRs.

This should make it easier for you to contribute however :)
I can even give you npm release rights, I guess!

**Comment by divyenduz** [comment]
@TimDaub: Thanks :) 

Yes, I will come up with more improvements, some of them will require some discussion which we can conduct via issues. 

I am working on a hobby resume builder on top of `json-resume` and I love `paper` as a theme, it will be the primary :)

**Pull request merged**
